name: CI

on:
  push:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: set up environment
        run: |
          python -m venv env
          source env/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install pytest
        
      - name: Run tests
        run: |
          pytest --junitxml=test-results.xml